"""Add camera_status to CameraScan model

Revision ID: 1ff3506cb500
Revises: 69666bc7835c
Create Date: 2024-07-12 15:22:11.659425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff3506cb500'
down_revision = '69666bc7835c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('camera_status', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_name'], ['camera.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera_scan')
    # ### end Alembic commands ###
