"""Changed Notifications to Notification

Revision ID: 4918f1fb5251
Revises: 9aeb0cc52650
Create Date: 2024-06-24 17:19:23.574302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4918f1fb5251'
down_revision = '9aeb0cc52650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
