"""Add country column to User model

Revision ID: 69666bc7835c
Revises: ed1165f63c93
Create Date: 2024-07-11 14:13:10.203434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69666bc7835c'
down_revision = 'ed1165f63c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=False, server_default='default_country'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
